#!/bin/bash

#busca un proceso especifico
DATO=`ps -aux | grep -v grep | grep listen.py`
if [ -z "$DATO" ]; then
    	EXISTE=false
else
	EXISTE=true
fi

START="start"
STOP="stop"

# echo "EXISTE: " $EXISTE
# start listen.py
if [[ $1 = $START ]]; then
	if $EXISTE = true;
	then
		echo "listen.py is already running"
	else
		echo "launching listen.py"
		/home/pi/Documents/Python\ projects/listen.py > /dev/null &
	fi
fi

# stop PiCmd
if [[ $1 = $STOP ]];
then
	if $EXISTE = true;
	then
		kill -9 `ps -ef |grep -v grep |grep listen.py| awk '{print $2}'`
		echo "listen.py stoped"
	else
		echo "listen.py was not running"
	fi
fi
