#!/bin/bash

#busca un proceso especifico
DATO=`ps -aux | grep -v grep | grep findFace.py`
if [ -z "$DATO" ]; then
    	EXISTE=false
else
	EXISTE=true
fi

START="start"
STOP="stop"

# echo "EXISTE: " $EXISTE
# start findFace.py
if [[ $1 = $START ]]; then
	if $EXISTE = true;
	then
		echo "findFace.py is already running"
	else
		echo "launching findFace.py"
		cd "/home/pi/Documents/Python projects"
		./findFace.py /dev/null &
	fi
fi

# stop PiCmd
if [[ $1 = $STOP ]];
then
	if $EXISTE = true;
	then
		kill -9 `ps -ef |grep -v grep |grep findFace.py| awk '{print $2}'`
		echo "findFace.py stoped"
	else
		echo "findFace.py was not running"
	fi
fi
