#!/bin/bash

#busca un proceso especifico
DATO=`ps -aux | grep -v grep | grep say.py`
if [ -z "$DATO" ]; then
    	EXISTE=false
else
	EXISTE=true
fi

START="start"
STOP="stop"

# echo "EXISTE: " $EXISTE
# start say.py
if [[ $1 = $START ]]; then
	if $EXISTE = true;
	then
		echo "say.py is already running"
	else
		echo "launching say.py"
		/home/pi/Documents/Python\ projects/say.py > /dev/null &
	fi
fi

# stop PiCmd
if [[ $1 = $STOP ]];
then
	if $EXISTE = true;
	then
		kill -9 `ps -ef |grep -v grep |grep say.py| awk '{print $2}'`
		echo "say.py stoped"
	else
		echo "say.py was not running"
	fi
fi
